### ISSUE TITLE
Store user data in the BE

### ISSUE THREAD

**Issue by ghost** [Access-America/Citizen-Center#75]
We need the ability to store user data. A backend data model for users needs to be constructed, with the ability to expand upon this model for future additions.

**Comment by erichydrick** [comment]
So this is going to need some discussion, because the defining concept around the decision to use a distributed ID system is the data we _aren't_ storing in the database. Ideally, we'd just have an email address, password hash, and whatever data we need to pull information from the distributed ID store. To start with, we could just go with an email address and password hash. 

That said, we need to think about what data we want to store and what our access pattern are going to be. I know there was talk about using DynamoDB on AWS, and I don't know if Azure has something similar or not. My issue with that is DynamoDB is a good document lookup service, but terrible for running queries. I think we should use something like MongoDB which would be a similar document-based database and gives us flexibility both in schema and querying data. If Azure has something similar to DocumentDB from AWS we could use that as a managed database, or maybe something like Mongo Atlas.

**Comment by dboulet01** [comment]
User data would be stored with the Identity provider. We should try to store very little data on the user if any. Cosmos DB is a close comparison to DocumentDB.

**Comment by ricky-sb** [comment]
DynamoDB (and NoSQL in general) is great if you know your access patterns *up front*. ([Rick Houlihan has a great talk on it](https://www.youtube.com/watch?v=HaEPXoXVf2k)).  

Since we're not using AWS, Cosmos DB seems like a reasonable alternative. The schema is fairly simple and our access patterns aren't complicated.  

Where we really want to be focused is the type of data we're storing. Ideally, we'd get to the point where the [entire database could be leaked](https://signal.org/blog/looking-back-as-the-world-moves-forward/) and nothing would happen.
